import type { Location } from '../types/types';

export const estados: Location[] = [
  { id: 11, nome: 'Rondônia' },
  { id: 12, nome: 'Acre' },
  { id: 13, nome: 'Amazonas' },
  { id: 14, nome: 'Roraima' },
  { id: 15, nome: 'Pará' },
  { id: 16, nome: 'Amapá' },
  { id: 17, nome: 'Tocantins' },
  { id: 21, nome: 'Maranhão' },
  { id: 22, nome: 'Piauí' },
  { id: 23, nome: 'Ceará' },
  { id: 24, nome: 'Rio Grande do Norte' },
  { id: 25, nome: 'Paraíba' },
  { id: 26, nome: 'Pernambuco' },
  { id: 27, nome: 'Alagoas' },
  { id: 28, nome: 'Sergipe' },
  { id: 29, nome: 'Bahia' },
  { id: 31, nome: 'Minas Gerais' },
  { id: 32, nome: 'Espírito Santo' },
  { id: 33, nome: 'Rio de Janeiro' },
  { id: 35, nome: 'São Paulo' },
  { id: 41, nome: 'Paraná' },
  { id: 42, nome: 'Santa Catarina' },
  { id: 43, nome: 'Rio Grande do Sul' },
  { id: 50, nome: 'Mato Grosso do Sul' },
  { id: 51, nome: 'Mato Grosso' },
  { id: 52, nome: 'Goiás' },
  { id: 53, nome: 'Distrito Federal' },
];
