import type { Estado } from '../types';

export const estadosBrasil: Estado[] = [
  { id_estado: 11, estado: 'Rondônia' },
  { id_estado: 12, estado: 'Acre' },
  { id_estado: 13, estado: 'Amazonas' },
  { id_estado: 14, estado: 'Roraima' },
  { id_estado: 15, estado: 'Pará' },
  { id_estado: 16, estado: 'Amapá' },
  { id_estado: 17, estado: 'Tocantins' },
  { id_estado: 21, estado: 'Maranhão' },
  { id_estado: 22, estado: 'Piauí' },
  { id_estado: 23, estado: 'Ceará' },
  { id_estado: 24, estado: 'Rio Grande do Norte' },
  { id_estado: 25, estado: 'Paraíba' },
  { id_estado: 26, estado: 'Pernambuco' },
  { id_estado: 27, estado: 'Alagoas' },
  { id_estado: 28, estado: 'Sergipe' },
  { id_estado: 29, estado: 'Bahia' },
  { id_estado: 31, estado: 'Minas Gerais' },
  { id_estado: 32, estado: 'Espírito Santo' },
  { id_estado: 33, estado: 'Rio de Janeiro' },
  { id_estado: 35, estado: 'São Paulo' },
  { id_estado: 41, estado: 'Paraná' },
  { id_estado: 42, estado: 'Santa Catarina' },
  { id_estado: 43, estado: 'Rio Grande do Sul' },
  { id_estado: 50, estado: 'Mato Grosso do Sul' },
  { id_estado: 51, estado: 'Mato Grosso' },
  { id_estado: 52, estado: 'Goiás' },
  { id_estado: 53, estado: 'Distrito Federal' },
];
